name: Create Diagram

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Visualize repository
              uses: githubocto/repo-visualizer
              with:
                  output-file: diagram.png
